// Code generated by MockGen. DO NOT EDIT.
// Source: router.go

// Package mock is a generated GoMock package.
package mock

import (
	burp "burp"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Service is a mock of Service interface.
type Service struct {
	ctrl     *gomock.Controller
	recorder *ServiceMockRecorder
}

// ServiceMockRecorder is the mock recorder for Service.
type ServiceMockRecorder struct {
	mock *Service
}

// NewService creates a new mock instance.
func NewService(ctrl *gomock.Controller) *Service {
	mock := &Service{ctrl: ctrl}
	mock.recorder = &ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Service) EXPECT() *ServiceMockRecorder {
	return m.recorder
}

// DeleteBeer mocks base method.
func (m *Service) DeleteBeer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBeer indicates an expected call of DeleteBeer.
func (mr *ServiceMockRecorder) DeleteBeer(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeer", reflect.TypeOf((*Service)(nil).DeleteBeer), ctx, name)
}

// GetBeerByName mocks base method.
func (m *Service) GetBeerByName(ctx context.Context, name string) (burp.Beer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBeerByName", ctx, name)
	ret0, _ := ret[0].(burp.Beer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBeerByName indicates an expected call of GetBeerByName.
func (mr *ServiceMockRecorder) GetBeerByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBeerByName", reflect.TypeOf((*Service)(nil).GetBeerByName), ctx, name)
}

// SaveBeer mocks base method.
func (m *Service) SaveBeer(ctx context.Context, beer burp.Beer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBeer", ctx, beer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBeer indicates an expected call of SaveBeer.
func (mr *ServiceMockRecorder) SaveBeer(ctx, beer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBeer", reflect.TypeOf((*Service)(nil).SaveBeer), ctx, beer)
}

// SearchBeers mocks base method.
func (m *Service) SearchBeers(ctx context.Context, filter burp.BeerFilter) ([]burp.Beer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBeers", ctx, filter)
	ret0, _ := ret[0].([]burp.Beer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchBeers indicates an expected call of SearchBeers.
func (mr *ServiceMockRecorder) SearchBeers(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBeers", reflect.TypeOf((*Service)(nil).SearchBeers), ctx, filter)
}

// MockBeerSaver is a mock of BeerSaver interface.
type MockBeerSaver struct {
	ctrl     *gomock.Controller
	recorder *MockBeerSaverMockRecorder
}

// MockBeerSaverMockRecorder is the mock recorder for MockBeerSaver.
type MockBeerSaverMockRecorder struct {
	mock *MockBeerSaver
}

// NewMockBeerSaver creates a new mock instance.
func NewMockBeerSaver(ctrl *gomock.Controller) *MockBeerSaver {
	mock := &MockBeerSaver{ctrl: ctrl}
	mock.recorder = &MockBeerSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeerSaver) EXPECT() *MockBeerSaverMockRecorder {
	return m.recorder
}

// SaveBeer mocks base method.
func (m *MockBeerSaver) SaveBeer(ctx context.Context, beer burp.Beer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBeer", ctx, beer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBeer indicates an expected call of SaveBeer.
func (mr *MockBeerSaverMockRecorder) SaveBeer(ctx, beer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBeer", reflect.TypeOf((*MockBeerSaver)(nil).SaveBeer), ctx, beer)
}

// MockBeerDeleter is a mock of BeerDeleter interface.
type MockBeerDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockBeerDeleterMockRecorder
}

// MockBeerDeleterMockRecorder is the mock recorder for MockBeerDeleter.
type MockBeerDeleterMockRecorder struct {
	mock *MockBeerDeleter
}

// NewMockBeerDeleter creates a new mock instance.
func NewMockBeerDeleter(ctrl *gomock.Controller) *MockBeerDeleter {
	mock := &MockBeerDeleter{ctrl: ctrl}
	mock.recorder = &MockBeerDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeerDeleter) EXPECT() *MockBeerDeleterMockRecorder {
	return m.recorder
}

// DeleteBeer mocks base method.
func (m *MockBeerDeleter) DeleteBeer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBeer indicates an expected call of DeleteBeer.
func (mr *MockBeerDeleterMockRecorder) DeleteBeer(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeer", reflect.TypeOf((*MockBeerDeleter)(nil).DeleteBeer), ctx, name)
}

// MockBeerGetter is a mock of BeerGetter interface.
type MockBeerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockBeerGetterMockRecorder
}

// MockBeerGetterMockRecorder is the mock recorder for MockBeerGetter.
type MockBeerGetterMockRecorder struct {
	mock *MockBeerGetter
}

// NewMockBeerGetter creates a new mock instance.
func NewMockBeerGetter(ctrl *gomock.Controller) *MockBeerGetter {
	mock := &MockBeerGetter{ctrl: ctrl}
	mock.recorder = &MockBeerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeerGetter) EXPECT() *MockBeerGetterMockRecorder {
	return m.recorder
}

// GetBeerByName mocks base method.
func (m *MockBeerGetter) GetBeerByName(ctx context.Context, name string) (burp.Beer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBeerByName", ctx, name)
	ret0, _ := ret[0].(burp.Beer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBeerByName indicates an expected call of GetBeerByName.
func (mr *MockBeerGetterMockRecorder) GetBeerByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBeerByName", reflect.TypeOf((*MockBeerGetter)(nil).GetBeerByName), ctx, name)
}

// MockBeerSearcher is a mock of BeerSearcher interface.
type MockBeerSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockBeerSearcherMockRecorder
}

// MockBeerSearcherMockRecorder is the mock recorder for MockBeerSearcher.
type MockBeerSearcherMockRecorder struct {
	mock *MockBeerSearcher
}

// NewMockBeerSearcher creates a new mock instance.
func NewMockBeerSearcher(ctrl *gomock.Controller) *MockBeerSearcher {
	mock := &MockBeerSearcher{ctrl: ctrl}
	mock.recorder = &MockBeerSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeerSearcher) EXPECT() *MockBeerSearcherMockRecorder {
	return m.recorder
}

// SearchBeers mocks base method.
func (m *MockBeerSearcher) SearchBeers(ctx context.Context, filter burp.BeerFilter) ([]burp.Beer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBeers", ctx, filter)
	ret0, _ := ret[0].([]burp.Beer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchBeers indicates an expected call of SearchBeers.
func (mr *MockBeerSearcherMockRecorder) SearchBeers(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBeers", reflect.TypeOf((*MockBeerSearcher)(nil).SearchBeers), ctx, filter)
}
